# Generated by Django 4.2.6 on 2026-01-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Full Name')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Code')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Email')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, default='BD', max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Fax')),
                ('previous_balance', models.FloatField(blank=True, default=0, null=True, verbose_name='Supplier Previous Balance')),
                ('category', models.CharField(blank=True, choices=[('Meat & Poultry', 'Meat & Poultry'), ('Herbs & Spices', 'Herbs & Spices'), ('Spices & Condiments', 'Spices & Condiments'), ('Fish & Seafood', 'Fish & Seafood'), ('Beverages & Dairy', 'Beverages & Dairy'), ('Vegetables & Fruits', 'Vegetables & Fruits'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=50, null=True, verbose_name='Supplier Category')),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person Name')),
                ('rating', models.FloatField(blank=True, default=0.0, help_text='Rating from 0.0 to 5.0', null=True, verbose_name='Supplier Rating')),
                ('totalPurchases', models.PositiveIntegerField(blank=True, default=0, help_text='Total number of purchase orders from this supplier', null=True, verbose_name='Total Number of Purchases')),
                ('totalSpent', models.FloatField(blank=True, default=0, help_text='Total amount spent on purchases from this supplier', null=True, verbose_name='Total Amount Spent')),
                ('paymentTerms', models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 20', 'Net 20'), ('Net 30', 'Net 30'), ('COD', 'Cash on Delivery'), ('Advance', 'Advance Payment')], default='Net 30', max_length=20, null=True, verbose_name='Payment Terms')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20, null=True, verbose_name='Supplier Status')),
                ('branchId', models.ManyToManyField(blank=True, help_text='Branches this user can access', to='company.branch')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['supplier_code'], name='suppliers_s_supplie_97d6e1_idx'), models.Index(fields=['status'], name='suppliers_s_status_e60785_idx'), models.Index(fields=['category'], name='suppliers_s_categor_6089e2_idx'), models.Index(fields=['companyId'], name='suppliers_s_company_4977ec_idx')],
            },
        ),
    ]
