# Generated by Django 4.2.6 on 2026-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('allDay', models.BooleanField(blank=True, default=False, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('start', models.IntegerField(blank=True, default=0, null=True)),
                ('end', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'calendar',
                'verbose_name_plural': 'calendars',
            },
        ),
    ]
