# Generated by Django 4.2.6 on 2026-01-13 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the promotion', max_length=200)),
                ('type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('bogo', 'Buy One Get One'), ('b2g1', 'Buy 2 Get 1'), ('combo', 'Combo / Bundle Price'), ('freeItem', 'Free Item')], default='percentage', help_text='Type of discount/promotion', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('code', models.CharField(help_text='Promotional code for customers', max_length=50, unique=True)),
                ('start_date', models.DateTimeField(help_text='When the promotion starts')),
                ('end_date', models.DateTimeField(help_text='When the promotion ends')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value to apply promotion', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(decimal_places=2, default=999999, help_text='Maximum discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(default=999999, help_text='Maximum number of times this promotion can be used')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this promotion has been used')),
                ('applicable_on', models.CharField(choices=[('all', 'All Items'), ('category', 'Specific Category'), ('item', 'Specific Item')], default='all', help_text='What the promotion applies to', max_length=20)),
                ('target_items', models.JSONField(blank=True, default=list, help_text='List of target item IDs or category IDs (JSON array)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='active', help_text='Current status of the promotion', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Specific branch (optional, null means all branches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='company.branch')),
                ('company', models.ForeignKey(help_text='Company this promotion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions_discounts_promotion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_value', models.DecimalField(decimal_places=2, help_text='Order value before discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer who used the promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Order where promotion was used', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='promotions_discounts.promotion')),
            ],
            options={
                'verbose_name': 'Promotion Usage',
                'verbose_name_plural': 'Promotion Usages',
                'db_table': 'promotions_discounts_usage',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions__code_1860a0_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status'], name='promotions__status_aea6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_85ec66_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['company'], name='promotions__company_ae61cf_idx'),
        ),
    ]
