# Generated by Django 4.2.6 on 2025-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions_discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage Off"),
                    ("fixed", "Fixed Amount Off"),
                    ("bogo", "Buy One Get One"),
                    ("b2g1", "Buy 2 Get 1"),
                    ("combo", "Combo / Bundle Price"),
                    ("freeItem", "Free Item"),
                ],
                default="percentage",
                help_text="Type of discount/promotion",
                max_length=20,
            ),
        ),
    ]
