# Generated by Django 4.2.6 on 2025-11-07 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
        ("recipe_waste_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
