# Generated by Copilot (manual migration)

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def prescription_upload_to(instance, filename: str) -> str:
    return f"assets/uploads/pharmacy/prescriptions/{instance.id}/{filename}"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("customers", "0001_initial"),
        ("products", "0002_inventoryitem_tracking_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updateAt", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "doctor_registration_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "clinic_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to=prescription_upload_to
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="company.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="customers.customer",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-createdAt"]},
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product_sku",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity_prescribed", models.PositiveIntegerField(default=1)),
                ("dosage_instructions", models.TextField(blank=True, null=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.prescription",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_items",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
