# Generated by Django 4.2.6 on 2025-12-27 05:03

from django.db import migrations, models
import pharmacy.models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=pharmacy.models.prescription_upload_to
            ),
        ),
    ]
