# Generated by Django 4.2.6 on 2026-01-13 19:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the reseller', max_length=100, verbose_name='Reseller Name')),
                ('companyName', models.CharField(help_text="Name of the reseller's company", max_length=150, verbose_name='Company Name')),
                ('email', models.EmailField(help_text='Primary email address for communication', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801XXXXXX'. Up to 14 digits allowed.", regex='^(?:\\+88|88)?(01[3-9]\\d{8})$')], verbose_name='Phone Number')),
                ('address', models.TextField(help_text='Complete address of the reseller', verbose_name='Address')),
                ('city', models.CharField(help_text='City where reseller is located', max_length=100, verbose_name='City')),
                ('country', models.CharField(help_text='Country where reseller operates', max_length=100, verbose_name='Country')),
                ('defaultCommission', models.DecimalField(decimal_places=2, help_text='Default commission percentage for this reseller', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Commission (%)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Current status of the reseller', max_length=20, verbose_name='Status')),
                ('totalClients', models.PositiveIntegerField(default=0, help_text='Total number of clients managed by this reseller', verbose_name='Total Clients')),
                ('totalRevenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated from all clients', max_digits=12, verbose_name='Total Revenue')),
                ('commissionEarned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commission earned by this reseller', max_digits=12, verbose_name='Commission Earned')),
                ('joinedDate', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when reseller joined the platform', verbose_name='Joined Date')),
                ('lastActive', models.DateTimeField(auto_now=True, help_text='Last time reseller was active', verbose_name='Last Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseller',
                'verbose_name_plural': 'Resellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_amount', models.DecimalField(decimal_places=2, help_text='Amount of revenue that generated this commission', max_digits=12, verbose_name='Revenue Amount')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate applied for this transaction', max_digits=5, verbose_name='Commission Rate (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Actual commission amount earned', max_digits=12, verbose_name='Commission Amount')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this commission has been paid', verbose_name='Is Paid')),
                ('paid_date', models.DateTimeField(blank=True, help_text='Date when commission was paid', null=True, verbose_name='Paid Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_company', models.ForeignKey(help_text='Company that generated this commission', on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Client Company')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='reseller.reseller', verbose_name='Reseller')),
            ],
            options={
                'verbose_name': 'Reseller Commission',
                'verbose_name_plural': 'Reseller Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['email'], name='reseller_re_email_e06f74_idx'),
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['status'], name='reseller_re_status_885162_idx'),
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['joinedDate'], name='reseller_re_joinedD_fa3ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='resellercommission',
            index=models.Index(fields=['reseller', 'is_paid'], name='reseller_re_reselle_c12e22_idx'),
        ),
        migrations.AddIndex(
            model_name='resellercommission',
            index=models.Index(fields=['created_at'], name='reseller_re_created_318e1a_idx'),
        ),
    ]
