# Generated by Django 4.2.6 on 2026-03-07 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_customer_notified', models.BooleanField(default=False)),
                ('is_supplier_notified', models.BooleanField(default=False)),
                ('damaged_date', models.DateField()),
                ('damaged_reason', models.CharField(choices=[('broken', 'Broken'), ('missing', 'Missing'), ('expiry dates over', 'Expiry Dates over'), ('empty', 'Empty')], max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
