# Generated by Django 4.2.6 on 2026-01-13 19:29

import authenticator.manager
import authenticator.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Owner Name')),
                ('role', models.CharField(blank=True, choices=[('software_owner', 'Software Owner'), ('reseller', 'Reseller'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('cashier', 'Cashier'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CEO', 'CEO'), ('Managing Director', 'Managing Director'), ('Chairman', 'Chairman'), ('Salesman', 'Salesman'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Quality Assurance Specialist', 'Quality Assurance Specialist'), ('Customer Service Associate', 'Customer Service Associate'), ('Sales Representative', 'Sales Representative'), ('Operations Manager', 'Operations Manager'), ('Marketing Director', 'Marketing Director'), ('Customer', 'Customer'), ('Employee', 'Employee'), ('Supplier', 'Supplier'), ('Auditor', 'Auditor'), ('Founder', 'Founder')], default='', max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fullAddress', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('addressType', models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Wirehouse', 'Wirehouse'), ('Other', 'Other')], default='', max_length=100, null=True)),
                ('primary', models.BooleanField(blank=True, default=False, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('banned', 'banned'), ('pending', 'pending'), ('rejected', 'rejected')], default='', max_length=100, null=True)),
                ('zipCode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('about', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Name')),
                ('companyAddress', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('business', models.CharField(blank=True, choices=[('ADVERTISING', 'ADVERTISING'), ('AGRICULTURE', 'AGRICULTURE'), ('APPAREL & ACCESSORIES', 'APPAREL & ACCESSORIES'), ('AUTOMOTIVE', 'AUTOMOTIVE'), ('BANKING', 'BANKING'), ('BIOTECHNOLOGY', 'BIOTECHNOLOGY'), ('BUILDING MATERIALS & EQUIPMENT', 'BUILDING MATERIALS & EQUIPMENT'), ('CHEMICAL', 'CHEMICAL'), ('COMPUTER', 'COMPUTER'), ('EDUCATION', 'EDUCATION'), ('ELECTRONICS', 'ELECTRONICS'), ('ENERGY', 'ENERGY'), ('ENTERTAINMENT & LEISURE', 'ENTERTAINMENT & LEISURE'), ('FINANCE', 'FINANCE'), ('FOOD & BEVERAGE', 'FOOD & BEVERAGE'), ('GROCERY', 'GROCERY'), ('HEALTHCARE', 'HEALTHCARE'), ('INSURANCE', 'INSURANCE'), ('LEGAL', 'LEGAL'), ('MANUFACTURING', 'MANUFACTURING'), ('PUBLISHING', 'PUBLISHING'), ('REAL ESTATE', 'REAL ESTATE'), ('SERVICE', 'SERVICE'), ('SOFTWARE', 'SOFTWARE'), ('SPORTS', 'SPORTS'), ('TECHNOLOGY', 'TECHNOLOGY'), ('TELECOMMUNICATIONS', 'TELECOMMUNICATIONS'), ('TELEVISION', 'TELEVISION'), ('TRANSPORTATION', 'TRANSPORTATION'), ('VENTURE CAPITAL', 'VENTURE CAPITAL')], help_text='Select your business type:', max_length=50, null=True, verbose_name='Business')),
                ('business_manager_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Manager Name')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to=authenticator.models.upload_to_beand_logo)),
                ('defaultURL', models.URLField(blank=True, null=True)),
                ('avatarUrl', models.ImageField(blank=True, null=True, upload_to=authenticator.models.upload_to_avater)),
                ('otp', models.SmallIntegerField(blank=True, help_text='One Time Password', null=True)),
                ('token', models.CharField(blank=True, editable=False, help_text='Token for authentication', max_length=100, null=True, unique=True, verbose_name='Token')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP Address', null=True, verbose_name='IP Address')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has been verified.Un-verified users cannot log in.', verbose_name='verified')),
                ('is_founder', models.BooleanField(default=False, help_text='Designates whether this user should be treated as founder.', verbose_name='founder')),
                ('is_ceo', models.BooleanField(default=False, help_text='Designates whether this user should be treated as CEO.', verbose_name='ceo')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether this user should be treated as admin.', verbose_name='admin')),
                ('is_manager', models.BooleanField(default=False, help_text='Designates whether this user should be treated as manager.', verbose_name='manager')),
                ('is_head_office', models.BooleanField(default=False, help_text='Designates whether this user should be treated as head office.', verbose_name='head office')),
                ('is_hr', models.BooleanField(default=False, help_text='Designates whether this user should be treated as Human resources (HR).', verbose_name='hr')),
                ('is_accountant', models.BooleanField(default=False, help_text='Designates whether this user should be treated as accountant.', verbose_name='accountant')),
                ('is_auditor', models.BooleanField(default=False, help_text='Designates whether this user should be treated as auditor.', verbose_name='auditor')),
                ('is_auditor_manager', models.BooleanField(default=False, help_text='Designates whether this user should be treated as auditor manager.', verbose_name='auditor manager')),
                ('is_auditor_head_office', models.BooleanField(default=False, help_text='Designates whether this user should be treated as auditor head office.', verbose_name='auditor head office')),
                ('is_employee', models.BooleanField(default=False, help_text='Designates whether this user should be treated as employee.', verbose_name='employee')),
                ('is_customer', models.BooleanField(default=False, help_text='Designates whether this user should be treated as customer.', verbose_name='customer')),
                ('is_supplier', models.BooleanField(default=False, help_text='Designates whether this user should be treated as supplier.', verbose_name='supplier')),
                ('otp_created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='OTP created time')),
                ('password_changes_datatime', models.DateTimeField(blank=True, null=True, verbose_name='Password changes datatime')),
                ('login_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Login datetime')),
                ('logout_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Logout datetime')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last activity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fullName', models.CharField(blank=True, help_text='Full display name', max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', authenticator.manager.UserManager()),
            ],
        ),
    ]
