# Generated by Django 4.2.6 on 2026-01-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reseller', '0001_initial'),
        ('sessions', '0001_initial'),
        ('company', '0001_initial'),
        ('authenticator', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branchAccess',
            field=models.ManyToManyField(blank=True, help_text='Branches this user can access', to='company.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='companyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.setemployeepayroll'),
        ),
        migrations.AddField(
            model_name='user',
            name='resellerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reseller.reseller'),
        ),
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
