# Generated by Django 4.2.6 on 2026-03-07 04:01

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import my_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Programming/Technology'), ('2', 'Health/Fitness'), ('3', 'Personal'), ('4', 'Fashion'), ('5', 'Food'), ('6', 'Travel'), ('7', 'Business'), ('8', 'Art'), ('9', 'Other')], default='1', max_length=20)),
                ('metaTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('coverUrl', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('imgUrla', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('imgUrlb', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('imgUrlc', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('imgUrld', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('imgUrle', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('imgUrlf', models.ImageField(blank=True, null=True, upload_to=my_project.models.upload_to_project)),
                ('publish', models.CharField(blank=True, choices=[('published', 'published'), ('draft', 'draft'), ('All', 'All')], default='published', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('signed', 'signed'), ('draft', 'draft'), ('all', 'all')], default='draft', max_length=100, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
