# Generated by Django 4.2.6 on 2025-11-06 22:38

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1", "Programming/Technology"),
                            ("2", "Health/Fitness"),
                            ("3", "Personal"),
                            ("4", "Fashion"),
                            ("5", "Food"),
                            ("6", "Travel"),
                            ("7", "Business"),
                            ("8", "Art"),
                            ("9", "Other"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("metaTitle", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "metaDescription",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "coverUrl",
                    models.ImageField(
                        blank=True, null=True, upload_to=blog.models.upload_to_blog
                    ),
                ),
                (
                    "metaKeywords",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "publish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("published", "published"),
                            ("draft", "draft"),
                            ("All", "All"),
                        ],
                        default="published",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("totalViews", models.IntegerField(blank=True, default=0, null=True)),
                ("totalShares", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "totalComments",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "totalFavorites",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="post_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="FavouritePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posts", models.ManyToManyField(to="blog.post")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "avatarUrl",
                    models.ImageField(
                        blank=True, null=True, upload_to=blog.models.upload_to_blog
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("postedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replyComment",
                        to="blog.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-postedAt"],
            },
        ),
    ]
