# Generated by Django 4.2.6 on 2025-11-06 22:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import service.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kitchen cabinet", "kitchen cabinet"),
                            ("wall cabinet", "wall cabinet"),
                            ("Living", "Living"),
                            ("TV cabinet", "TV cabinet"),
                            ("CNC design", "CNC Design"),
                        ],
                        default="Living",
                        max_length=20,
                    ),
                ),
                ("metaTitle", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default="Royal Park", max_length=200, null=True
                    ),
                ),
                (
                    "metaDescription",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "coverUrl",
                    models.ImageField(
                        blank=True, null=True, upload_to=service.models.upload_to_blog
                    ),
                ),
                (
                    "metaKeywords",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "publish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("published", "published"),
                            ("draft", "draft"),
                            ("All", "All"),
                        ],
                        default="published",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("charge", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "vat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=2.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
