# Generated by Django 4.2.6 on 2026-01-13 19:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('supplies', 'Supplies'), ('licenses', 'Licenses & Permits'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', help_text='Expense category', max_length=50)),
                ('description', models.CharField(help_text='Expense description', max_length=500)),
                ('vendor', models.CharField(help_text='Vendor or supplier name', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expense amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('auto_debit', 'Auto-debit'), ('check', 'Check'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('rocket', 'Rocket')], default='cash', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=50)),
                ('recurring', models.BooleanField(default=False, help_text='Is this a recurring expense?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('expense_date', models.DateField(default=django.utils.timezone.now, help_text='Date of expense')),
                ('due_date', models.DateField(blank=True, help_text='Due date for payment', null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('expenseNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_type', models.CharField(blank=True, max_length=100, null=True)),
                ('subTotal', models.FloatField(blank=True, default=0, null=True)),
                ('totalAmount', models.FloatField(blank=True, default=0, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('totalQty', models.IntegerField(blank=True, default=0, null=True)),
                ('advance', models.FloatField(blank=True, default=0, null=True)),
                ('due', models.FloatField(blank=True, default=0, null=True)),
                ('cashAmount', models.FloatField(blank=True, default=0, null=True)),
                ('dueDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('service', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('code', models.IntegerField(blank=True, default=0, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expense_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expense.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
