# Generated by Django 4.2.6 on 2026-01-13 19:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.CharField(choices=[('kitchen cabinet', 'kitchen cabinet'), ('wall cabinet', 'wall cabinet'), ('Living', 'Living'), ('TV cabinet', 'TV cabinet'), ('CNC design', 'CNC Design')], default='Living', max_length=20)),
                ('metaTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('author', models.CharField(blank=True, default='Royal Park', max_length=200, null=True)),
                ('metaDescription', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('coverUrl', models.ImageField(blank=True, null=True, upload_to=review.models.upload_to_blog)),
                ('metaKeywords', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('publish', models.CharField(blank=True, choices=[('published', 'published'), ('draft', 'draft'), ('All', 'All')], default='published', max_length=100, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
