# Generated by Django 4.2.6 on 2026-03-07 04:01

import customers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models.common_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('decsription', models.CharField(max_length=255, verbose_name='Description')),
                ('voucher_no', models.CharField(default=utils.models.common_fields.generate_voucher_no, max_length=14, unique=True, verbose_name='Voucher No')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Credit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Customer Name')),
                ('customer_code', models.CharField(blank=True, help_text='Auto-generated customer code (e.g., CUST001)', max_length=50, null=True, unique=True, verbose_name='Customer Code')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('category', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('corporate', 'Corporate'), ('consulate', 'Consulate')], default='regular', help_text='Customer type classification', max_length=20, verbose_name='Customer Category')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20, verbose_name='Customer Status')),
                ('totalOrders', models.PositiveIntegerField(default=0, help_text='Total number of orders placed by customer', verbose_name='Total Orders')),
                ('totalSpent', models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent by customer', max_digits=10, verbose_name='Total Amount Spent')),
                ('loyaltyPoints', models.PositiveIntegerField(default=0, help_text='Accumulated loyalty points', verbose_name='Loyalty Points')),
                ('lastVisit', models.DateField(auto_now_add=True, help_text="Date of customer's last visit", verbose_name='Last Visit Date')),
                ('fullAddress', models.TextField(blank=True, max_length=500, null=True, verbose_name='Full Address')),
                ('addressType', models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Wirehouse', 'Wirehouse'), ('Other', 'Other')], default='Home', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=200, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('primary', models.BooleanField(blank=True, default=False, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('avatarUrl', models.ImageField(blank=True, null=True, upload_to=customers.models.upload_to_customer)),
                ('notes', models.TextField(blank=True, help_text='Special preferences, allergies, etc.', max_length=1000, null=True, verbose_name='Customer Notes')),
                ('othercompany', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['customer_code'], name='customers_c_custome_116ac0_idx'), models.Index(fields=['phoneNumber'], name='customers_c_phoneNu_150b0c_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['category'], name='customers_c_categor_f85c24_idx'), models.Index(fields=['status'], name='customers_c_status_ce44cf_idx'), models.Index(fields=['lastVisit'], name='customers_c_lastVis_31d8fa_idx')],
            },
        ),
    ]
