# Generated by Django 4.2.6 on 2025-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="04097477618753",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
