# Generated by Django 4.2.6 on 2025-11-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_ledger_voucher_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="othercompany",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="29371311208064",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
