# Generated by Django 4.2.6 on 2025-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_othercompany_alter_ledger_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="16462607032952",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
