# Generated by Django 4.2.6 on 2025-12-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_alter_ledger_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="54862006286362",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
