# Generated by Django 4.2.6 on 2025-12-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0014_alter_ledger_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="95100757083447",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
