# Generated by Django 4.2.6 on 2025-12-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("customers", "0015_alter_ledger_voucher_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.branch",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="companyId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="44168950661573",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
