# Generated by Django 4.2.6 on 2025-12-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_customer_branch_customer_companyid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default="25182302859074",
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
