# Generated by Django 4.2.6 on 2025-12-21 20:32

from django.db import migrations, models
import utils.models.common_fields


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0017_alter_ledger_voucher_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="voucher_no",
            field=models.CharField(
                default=utils.models.common_fields.generate_voucher_no,
                max_length=14,
                unique=True,
                verbose_name="Voucher No",
            ),
        ),
    ]
