# Generated by Django 4.2.6 on 2026-01-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetEmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.FloatField(default=0)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'cash'), ('bank', 'bank')], default='cash', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('paid', 'paid'), ('advance', 'advance')], default='active', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverTimePayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee', models.ManyToManyField(blank=True, related_name='overtime_assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_overtime', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePaySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('paySlipNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('paid', 'paid'), ('advance', 'advance')], default='paid', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'cash'), ('bank', 'bank')], default='cash', max_length=100, null=True)),
                ('last_amount', models.FloatField(blank=True, default=0, null=True)),
                ('basic_salary', models.FloatField(default=0)),
                ('net_total', models.FloatField(default=0)),
                ('ta', models.FloatField(default=0)),
                ('da', models.FloatField(default=0)),
                ('ma', models.FloatField(default=0)),
                ('hra', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('e_other', models.FloatField(default=0)),
                ('total_earning', models.FloatField(blank=True, default=0, null=True)),
                ('tds', models.FloatField(default=0)),
                ('esi', models.FloatField(default=0)),
                ('pf', models.FloatField(default=0)),
                ('leave', models.FloatField(default=0)),
                ('d_other', models.FloatField(default=0)),
                ('total_deduction', models.FloatField(blank=True, default=0, null=True)),
                ('payroll_month', models.DateTimeField(blank=True, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_employee_payslip_model', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_payslip_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionPayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee', models.ManyToManyField(blank=True, related_name='deduction_assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_deduction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
                ('assignee', models.ManyToManyField(blank=True, related_name='base_assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_base_payroll_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionPayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Remuneration', 'Remuneration'), ('Additional Remuneration', 'Additional Remuneration'), ('Other', 'Other')], default='Remuneration', max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
                ('assignee', models.ManyToManyField(blank=True, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_addition_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
