# Generated by Django 4.2.6 on 2026-03-07 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu category', max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Description of this menu category', null=True, verbose_name='Category Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active', verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which categories are displayed', verbose_name='Display Order')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, help_text='Auto-generated item code (e.g., ITEM001)', max_length=50, null=True, unique=True, verbose_name='Item Code')),
                ('name', models.CharField(db_index=True, help_text='Name of the menu item', max_length=200, verbose_name='Menu Item Name')),
                ('category', models.CharField(db_index=True, default='General', help_text='Category of the menu item', max_length=100, verbose_name='Category')),
                ('price', models.FloatField(help_text='Selling price of the menu item in BDT', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Selling Price')),
                ('cost', models.FloatField(help_text='Cost price of the menu item in BDT', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Price')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the menu item', null=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for display purposes', max_length=500, null=True, verbose_name='Short Description')),
                ('available', models.BooleanField(db_index=True, default=True, help_text='Whether this item is available for ordering', verbose_name='Available')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this item is featured on the menu', verbose_name='Featured Item')),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Estimated preparation time in minutes', verbose_name='Preparation Time')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Estimated calories per serving', null=True, verbose_name='Calories')),
                ('ingredients', models.TextField(blank=True, help_text='List of ingredients used in this item', null=True, verbose_name='Ingredients')),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Whether this item is vegetarian', verbose_name='Vegetarian')),
                ('is_vegan', models.BooleanField(default=False, help_text='Whether this item is vegan', verbose_name='Vegan')),
                ('contains_gluten', models.BooleanField(default=False, help_text='Whether this item contains gluten', verbose_name='Contains Gluten')),
                ('total_sold', models.PositiveIntegerField(default=0, help_text='Total number of times this item has been sold', verbose_name='Total Sold')),
                ('total_revenue', models.FloatField(default=0, help_text='Total revenue generated from this item', verbose_name='Total Revenue')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which items are displayed in the category', verbose_name='Display Order')),
                ('image', models.ImageField(blank=True, help_text='Image of the menu item', null=True, upload_to='menu_items/', verbose_name='Item Image')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['-created_at', 'display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='menu_items__name_506695_idx'), models.Index(fields=['item_code'], name='menu_items__item_co_32ce31_idx'), models.Index(fields=['category'], name='menu_items__categor_115521_idx'), models.Index(fields=['available'], name='menu_items__availab_149e07_idx'), models.Index(fields=['price'], name='menu_items__price_435ef1_idx'), models.Index(fields=['cost'], name='menu_items__cost_439c98_idx'), models.Index(fields=['is_featured'], name='menu_items__is_feat_d6aadc_idx'), models.Index(fields=['total_sold'], name='menu_items__total_s_483d09_idx')],
            },
        ),
    ]
