# Generated by Django 4.2.6 on 2026-03-07 04:01

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('companyId', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fullAddress', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('avatarUrl', models.ImageField(blank=True, null=True, upload_to=company.models.upload_to)),
                ('url', models.URLField(blank=True, null=True)),
                ('postedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=company.models.upload_to)),
                ('ownerName', models.CharField(blank=True, help_text='Company owner name', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, help_text='Alternative phone field', max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Alternative address field', max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('industry', models.CharField(blank=True, choices=[('fine_dining', 'Fine Dining'), ('fast_food', 'Fast Food'), ('cafe', 'Cafe'), ('bar', 'Bar'), ('cloud_kitchen', 'Cloud Kitchen'), ('multi_cuisine', 'Multi Cuisine')], help_text='Industry type', max_length=100, null=True)),
                ('branch_count_field', models.IntegerField(blank=True, help_text='Number of branches (stored field)', null=True)),
                ('activeUsers', models.IntegerField(blank=True, help_text='Number of active users', null=True)),
                ('monthlyRevenue', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly revenue', max_digits=15, null=True)),
                ('subscriptionPlan', models.CharField(blank=True, choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], help_text='Subscription plan (basic, professional, enterprise)', max_length=50, null=True)),
                ('subscriptionStatus', models.CharField(blank=True, choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('payment_overdue', 'Payment Overdue'), ('pending_approval', 'Pending Approval'), ('pending_payment', 'Pending Payment')], help_text='Current subscription status', max_length=50, null=True)),
                ('subscriptionPrice', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price', max_digits=10, null=True)),
                ('lastPaymentDate', models.DateTimeField(blank=True, help_text='Date of last payment', null=True)),
                ('nextBillingDate', models.DateTimeField(blank=True, help_text='Next billing date', null=True)),
                ('paymentMethod', models.CharField(blank=True, help_text='Payment method (Credit Card, Bank Transfer, etc.)', max_length=100, null=True)),
                ('daysOverdue', models.IntegerField(blank=True, help_text='Number of days payment is overdue', null=True)),
                ('trialEndsAt', models.DateTimeField(blank=True, help_text='Trial end date', null=True)),
                ('resellerId', models.CharField(blank=True, help_text='ID of reseller who sold this company', max_length=100, null=True)),
                ('resellerCommission', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage for reseller', max_digits=5, null=True)),
                ('approvalStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Approval status', max_length=50, null=True)),
                ('approvalDate', models.DateTimeField(blank=True, help_text='Date when company was approved/rejected', null=True)),
                ('approvedBy', models.CharField(blank=True, help_text='Who approved/rejected the company', max_length=200, null=True)),
                ('rejectionReason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('paymentType', models.CharField(blank=True, choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Payment frequency', max_length=50, null=True)),
                ('initialPaymentAmount', models.DecimalField(blank=True, decimal_places=2, help_text='Initial payment amount', max_digits=10, null=True)),
                ('initialPaymentStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], help_text='Initial payment verification status', max_length=50, null=True)),
                ('initialPaymentDate', models.DateTimeField(blank=True, help_text='Date of initial payment', null=True)),
                ('initialPaymentMethod', models.CharField(blank=True, help_text='Method used for initial payment', max_length=100, null=True)),
                ('initialPaymentTransactionId', models.CharField(blank=True, help_text='Transaction ID for initial payment', max_length=200, null=True)),
                ('setupFee', models.DecimalField(blank=True, decimal_places=2, help_text='Setup fee amount', max_digits=10, null=True)),
                ('setupFeeStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], help_text='Setup fee payment status', max_length=50, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lastActive', models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of enabled features (e.g., ['pos', 'inventory', 'booking'])")),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-postedAt'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryColor', models.CharField(blank=True, help_text='Primary color in hex format (e.g., #8B4513)', max_length=7, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3, null=True)),
                ('taxRate', models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate percentage', max_digits=5, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Timezone (e.g., America/New_York)', max_length=100, null=True)),
                ('enforce_prescriptions', models.BooleanField(default=False, help_text='If enabled, prescription-required products cannot be sold unless an approved prescription is attached.')),
                ('enforce_controlled_substances', models.BooleanField(default=False, help_text='If enabled, controlled substances additionally require an approved prescription.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(help_text='Company these customizations belong to', on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='company.company')),
            ],
            options={
                'verbose_name': 'Company Customization',
                'verbose_name_plural': 'Company Customizations',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name (e.g., Downtown Branch, Mall Location)', max_length=100)),
                ('code', models.CharField(help_text='Unique branch code (e.g., DT001, ML002)', max_length=20, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, help_text='Alternative phone field', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fullAddress', models.CharField(help_text='Street address', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Frontend location field', max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_name', models.CharField(blank=True, help_text='Manager name (for frontend compatibility)', max_length=100, null=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text="Opening hours for each day (e.g., {'monday': '9:00-22:00'})")),
                ('openingHours', models.CharField(blank=True, help_text='Opening hours string for frontend', max_length=100, null=True)),
                ('seating_capacity', models.PositiveIntegerField(default=0, help_text='Total seating capacity')),
                ('delivery_radius', models.FloatField(default=0.0, help_text='Delivery radius in kilometers')),
                ('todaySales', models.DecimalField(decimal_places=2, default=0.0, help_text="Today's sales amount", max_digits=10)),
                ('monthSales', models.DecimalField(decimal_places=2, default=0.0, help_text="Current month's sales", max_digits=10)),
                ('activeOrders', models.PositiveIntegerField(default=0, help_text='Number of active orders')),
                ('activeTables', models.PositiveIntegerField(default=0, help_text='Number of active/occupied tables')),
                ('staff', models.PositiveIntegerField(default=0, help_text='Number of staff members')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Branch status for frontend compatibility', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('postedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='company_branches', to='company.company')),
                ('manager', models.ForeignKey(blank=True, help_text='Branch manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
