# Generated by Django 4.2.6 on 2025-11-06 22:38

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kitchen cabinet", "kitchen cabinet"),
                            ("wall cabinet", "wall cabinet"),
                            ("Living", "Living"),
                            ("TV cabinet", "TV cabinet"),
                            ("CNC design", "CNC Design"),
                        ],
                        default="Living",
                        max_length=20,
                    ),
                ),
                ("metaTitle", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default="Royal Park", max_length=200, null=True
                    ),
                ),
                (
                    "metaDescription",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "coverUrl",
                    models.ImageField(
                        blank=True, null=True, upload_to=portfolio.models.upload_to_blog
                    ),
                ),
                (
                    "imga",
                    models.ImageField(
                        blank=True, null=True, upload_to=portfolio.models.upload_to_blog
                    ),
                ),
                (
                    "imgb",
                    models.ImageField(
                        blank=True, null=True, upload_to=portfolio.models.upload_to_blog
                    ),
                ),
                (
                    "imgc",
                    models.ImageField(
                        blank=True, null=True, upload_to=portfolio.models.upload_to_blog
                    ),
                ),
                (
                    "imgd",
                    models.ImageField(
                        blank=True, null=True, upload_to=portfolio.models.upload_to_blog
                    ),
                ),
                (
                    "imge",
                    models.ImageField(
                        blank=True, null=True, upload_to=portfolio.models.upload_to_blog
                    ),
                ),
                (
                    "metaKeywords",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "publish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("published", "published"),
                            ("draft", "draft"),
                            ("All", "All"),
                        ],
                        default="published",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="TagDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
