# Generated by Django 4.2.6 on 2026-01-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'draft'), ('paid', 'paid'), ('pending', 'pending'), ('overdue', 'overdue')], default='draft', max_length=100, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
