# Generated by Django 4.2.6 on 2025-11-06 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("shipBy", models.CharField(blank=True, max_length=100, null=True)),
                ("speedy", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "trackingNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliverys",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completionTime", models.DateTimeField(blank=True, null=True)),
                ("deliveryTime", models.DateTimeField(blank=True, null=True)),
                (
                    "orderTime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("paymentTime", models.DateTimeField(blank=True, null=True)),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "Historys",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardNumber", models.CharField(blank=True, max_length=100, null=True)),
                ("cardType", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "paymentTime",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="ShippingAddres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullAddress",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phoneNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ShippingAddres",
                "verbose_name_plural": "ShippingAddress",
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "timeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="order.history",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline",
                "verbose_name_plural": "Timelines",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orderNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("shipping", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refunded", "refunded"),
                            ("cancelled", "cancelled"),
                            ("pending", "pending"),
                            ("completed", "completed"),
                        ],
                        default="draft",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("totalAmount", models.FloatField(blank=True, default=0, null=True)),
                ("subTotal", models.FloatField(blank=True, default=0, null=True)),
                ("taxes", models.FloatField(blank=True, default=0, null=True)),
                ("discount", models.FloatField(blank=True, default=0, null=True)),
                (
                    "totalQuantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="customers.customer",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="order.delivery",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="order.history",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="order.payment",
                    ),
                ),
                (
                    "shippingAddress",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shippingAddress",
                        to="order.shippingaddres",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverUrl",
                    models.ImageField(
                        blank=True, null=True, upload_to=order.models.upload_to
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "sku",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "service",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("code", models.IntegerField(blank=True, default=0, null=True)),
                ("duration", models.IntegerField(blank=True, default=0, null=True)),
                ("updateAt", models.DateTimeField(auto_now=True)),
                (
                    "createDate",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
