# Generated by Django 4.2.6 on 2026-03-07 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_id', models.CharField(blank=True, help_text='Menu Item UUID', max_length=100, null=True)),
                ('menu_item_code', models.CharField(blank=True, help_text='Menu Item Code', max_length=50, null=True)),
                ('title', models.CharField(help_text='Item name', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('category', models.CharField(blank=True, default='', help_text='Menu category', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for this item', max_digits=10)),
                ('service', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('code', models.IntegerField(blank=True, default=0, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('preparation_time', models.PositiveIntegerField(default=0, help_text='Preparation time in minutes')),
                ('special_instructions', models.TextField(blank=True, help_text='Special cooking instructions', null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='ordered', max_length=20)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['createDate'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card Payment'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_amount', models.FloatField(default=0, help_text='Total refund amount')),
                ('restocked_to_inventory', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('share_token', models.CharField(blank=True, help_text='Unique token for secure invoice sharing via QR code', max_length=64, null=True, unique=True)),
                ('order_type', models.CharField(choices=[('In-Store', 'In-Store'), ('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='In-Store', max_length=20)),
                ('table_number', models.CharField(blank=True, help_text='Table number for In-Store orders', max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card Payment'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('upay', 'Upay'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], default='cash', max_length=20, null=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('is_return', models.BooleanField(default=False, verbose_name='Is Returned')),
                ('is_return_adjusted', models.BooleanField(default=False, verbose_name='Is Refund Adjusted')),
                ('taxes', models.FloatField(default=10.0, help_text='Tax rate percentage')),
                ('taxes_value', models.FloatField(default=0, help_text='Calculated tax amount')),
                ('discount', models.FloatField(default=0, help_text='Discount rate percentage')),
                ('discount_amount', models.FloatField(default=0, help_text='Discount amount')),
                ('service_charge_rate', models.FloatField(default=0, help_text='Service charge rate percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('service_charge_amount', models.FloatField(default=0, help_text='Calculated service charge amount')),
                ('tip_amount', models.FloatField(default=0, help_text='Tip amount')),
                ('totalQty', models.IntegerField(default=0, help_text='Total quantity of items')),
                ('subTotal', models.FloatField(default=0, help_text='Subtotal before tax and discount')),
                ('totalAmount', models.FloatField(default=0, help_text='Final total amount')),
                ('advance', models.FloatField(blank=True, default=0, null=True)),
                ('due', models.FloatField(blank=True, default=0, null=True)),
                ('cashAmount', models.FloatField(blank=True, default=0, null=True)),
                ('shipping', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(default=0, help_text='Legacy total field')),
                ('currency', models.CharField(default='BDT', help_text='Currency code', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes', null=True)),
                ('estimated_preparation_time', models.PositiveIntegerField(default=0, help_text='Estimated prep time in minutes')),
                ('actual_preparation_time', models.PositiveIntegerField(blank=True, help_text='Actual prep time in minutes', null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True, help_text='When the order was placed')),
                ('ready_time', models.DateTimeField(blank=True, help_text='When the order was ready', null=True)),
                ('served_time', models.DateTimeField(blank=True, help_text='When the order was served', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('kot_printed', models.BooleanField(default=False, help_text='Whether KOT has been printed')),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
                ('invoiceFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceFrom', to=settings.AUTH_USER_MODEL)),
                ('invoiceTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceTo', to='customers.customer')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pharmacy.prescription')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='sales.invoiceitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.refund')),
            ],
        ),
        migrations.AddField(
            model_name='refund',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sell_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
    ]
