# Generated by GitHub Copilot on 2025-12-26

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0002_sale_branch_sale_companyid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="service_charge_rate",
            field=models.FloatField(
                default=0,
                help_text="Service charge rate percentage",
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="service_charge_amount",
            field=models.FloatField(
                default=0, help_text="Calculated service charge amount"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="tip_amount",
            field=models.FloatField(default=0, help_text="Tip amount"),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card Payment"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("upay", "Upay"),
                            ("rocket", "Rocket"),
                            ("bank_transfer", "Bank Transfer"),
                            ("digital_wallet", "Digital Wallet"),
                            ("cod", "Cash on Delivery"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "total_amount",
                    models.FloatField(default=0, help_text="Total refund amount"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_items",
                        to="sales.invoiceitem",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.refund",
                    ),
                ),
            ],
        ),
    ]
