# Generated by Django 4.2.6 on 2025-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_refund_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_refunded",
            field=models.BooleanField(default=False, verbose_name="Is Refunded"),
        ),
    ]
