# Generated by Django 4.2.6 on 2025-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_sale_is_refunded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="is_refunded",
            new_name="is_return",
        ),
        migrations.AddField(
            model_name="sale",
            name="is_return_adjusted",
            field=models.BooleanField(default=False, verbose_name="Is Refund Adjusted"),
        ),
    ]
