# Generated by Django 4.2.6 on 2025-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_rename_is_refunded_sale_is_return_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="is_return",
            field=models.BooleanField(default=False, verbose_name="Is Returned"),
        ),
    ]
