# Generated by Django 4.2.6 on 2026-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_sale_prescription_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("In-Store", "In-Store"),
                    ("Pickup", "Pickup"),
                    ("Delivery", "Delivery"),
                ],
                default="In-Store",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="table_number",
            field=models.CharField(
                blank=True,
                help_text="Table number for In-Store orders",
                max_length=50,
                null=True,
            ),
        ),
    ]
