# Generated by Django 4.2.6 on 2025-11-06 22:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models.product_model
import products.models.review_model
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inventory Category",
                "verbose_name_plural": "Inventory Categories",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "Good Stock"),
                            ("medium", "Medium Stock"),
                            ("low", "Low Stock"),
                            ("critical", "Critical Stock"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.inventorycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("content", models.CharField(default="New", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Kids", "Kids"),
                            ("Men", "Men"),
                            ("Women", "Women"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "publish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("published", "published"),
                            ("draft", "draft"),
                            ("All", "All"),
                        ],
                        default="published",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "inventoryType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("out of stock", "out of stock"),
                            ("low stock", "low stock"),
                            ("in stock", "in stock"),
                        ],
                        default="in stock",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subDescription",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("available", models.IntegerField(default=0)),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("priceSale", models.FloatField(blank=True, default=0, null=True)),
                ("regular_price", models.FloatField(blank=True, default=0, null=True)),
                ("taxes", models.FloatField(blank=True, default=0, null=True)),
                ("in_stock", models.IntegerField(default=0)),
                ("is_publish", models.BooleanField(default=False)),
                ("totalRatings", models.FloatField(blank=True, default=0, null=True)),
                ("totalSold", models.IntegerField(default=0)),
                ("totalReviews", models.FloatField(blank=True, default=0, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_model.upload_to,
                    ),
                ),
                (
                    "coverUrl",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_model.upload_to,
                    ),
                ),
                (
                    "barcode",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_model.upload_to_barcode,
                    ),
                ),
                (
                    "qrcode",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_model.upload_to_qrcode,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("out_of_stock", models.BooleanField(default=False)),
                (
                    "mfg_date",
                    models.DateField(
                        blank=True,
                        help_text="The MFG date is the date the product was manufactured, or the Manufacturing Date (MFG). It is not an expiration date.",
                        null=True,
                    ),
                ),
                (
                    "exp_date",
                    models.DateField(
                        blank=True,
                        help_text="An expiration date is the last day that a consumable product such as food or medicine.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("out of stock", "Out of Stock"),
                            ("in stock", "In Stock"),
                        ],
                        default="In stock",
                        max_length=20,
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        help_text="Bluetooth, Wi-Fi, USB, Ethernet, etc.",
                        max_length=40,
                        null=True,
                        verbose_name="Technology",
                    ),
                ),
                (
                    "uses_for_product",
                    models.CharField(
                        blank=True,
                        help_text="Personal, Gaming, Business, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Specific Uses For Product",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Example: Apple, Samsung, Sony, LG, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Brand Name",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Example: Apple, Samsung, LG, Sony, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        default=0,
                        help_text="The numeric or text version of the item's size. Example: Small, Medium, Large, X-Large, XX-Large, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Size",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="The numeric or text version of the item's weight. Example: 1.5 lbs, 2.5 lbs, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="Weight",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        help_text="The numeric or text version of the item's height. Example: 1.5 inches, 2.5 inches, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="Height",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#0000",
                        help_text="The color of the item. Example: Red, Blue, Green, etc.",
                        max_length=200,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        help_text="The shape of the item. Example: Round, Square, Oval, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="Shape",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        help_text="what material is the product made out of? '\n Example: plastic, metal, wood, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="Material Type",
                    ),
                ),
                ("count_sold", models.IntegerField(default=0)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country? '\n Example: BD, China, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                ("recently_sold", models.DateTimeField(blank=True, null=True)),
                ("recently_added", models.DateTimeField(blank=True, null=True)),
                ("recently_viewed", models.DateTimeField(blank=True, null=True)),
                ("recently_updated", models.DateTimeField(blank=True, null=True)),
                ("supplier_price", models.FloatField(blank=True, default=0, null=True)),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
                (
                    "newLabel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newLabel",
                        to="products.newlabel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SaleLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("content", models.CharField(default="Sale", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Taka", max_length=100, unique=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjustment", "Stock Adjustment"),
                            ("transfer", "Stock Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "previous_stock",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("new_stock", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="System", max_length=100)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="products.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("comment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "isPurchased",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                (
                    "avatarUrl",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.review_model.upload_to,
                    ),
                ),
                ("helpful", models.IntegerField(blank=True, default=0, null=True)),
                ("attachments", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "postedAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("starCount", models.IntegerField(blank=True, default=0, null=True)),
                ("reviewCount", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "createdAt",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updateAt", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="saleLabel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saleLabel",
                to="products.salelabel",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.size"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_item",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.unit"
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_model.upload_to_multi,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
