# Generated by Django 4.2.6 on 2026-01-13 19:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models.product_model
import products.models.review_model
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_names', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_categories', to='company.company')),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('good', 'Good Stock'), ('medium', 'Medium Stock'), ('low', 'Low Stock'), ('critical', 'Critical Stock'), ('out_of_stock', 'Out of Stock')], default='good', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('average_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='company.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.inventorycategory')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='company.company')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('content', models.CharField(default='New', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('low_stock_threshold', models.PositiveIntegerField(default=20)),
                ('track_batches', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Women', 'Women'), ('All', 'All')], default='All', max_length=100, null=True)),
                ('publish', models.CharField(blank=True, choices=[('published', 'published'), ('draft', 'draft'), ('All', 'All')], default='published', max_length=100, null=True)),
                ('inventoryType', models.CharField(blank=True, choices=[('out of stock', 'out of stock'), ('low stock', 'low stock'), ('in stock', 'in stock')], default='in stock', max_length=100, null=True)),
                ('subDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('available', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('priceSale', models.FloatField(blank=True, default=0, null=True)),
                ('regular_price', models.FloatField(blank=True, default=0, null=True)),
                ('taxes', models.FloatField(blank=True, default=0, null=True)),
                ('in_stock', models.IntegerField(default=0)),
                ('is_publish', models.BooleanField(default=False)),
                ('totalRatings', models.FloatField(blank=True, default=0, null=True)),
                ('totalSold', models.IntegerField(default=0)),
                ('totalPurchase', models.IntegerField(default=0, help_text='Cumulative purchased quantity added to stock (auto-incremented when receiving/purchasing).')),
                ('totalReviews', models.FloatField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_model.upload_to)),
                ('coverUrl', models.ImageField(blank=True, null=True, upload_to=products.models.product_model.upload_to)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to=products.models.product_model.upload_to_barcode)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to=products.models.product_model.upload_to_qrcode)),
                ('quantity', models.IntegerField(default=0)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('mfg_date', models.DateField(blank=True, help_text='The MFG date is the date the product was manufactured, or the Manufacturing Date (MFG). It is not an expiration date.', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='An expiration date is the last day that a consumable product such as food or medicine.', null=True)),
                ('prescription_required', models.BooleanField(default=False, help_text='True if sale requires an approved prescription (when enforcement is enabled).')),
                ('controlled_substance', models.BooleanField(default=False, help_text='True if item is controlled/regulated.')),
                ('dosage_form', models.CharField(blank=True, help_text='Tablet, Capsule, Syrup, Injection, Ointment, etc.', max_length=50, null=True)),
                ('strength', models.CharField(blank=True, help_text='Strength/dose, e.g. 500mg, 5mg/5ml, etc.', max_length=50, null=True)),
                ('mrp', models.FloatField(blank=True, default=0, help_text='Maximum Retail Price (MRP).', null=True)),
                ('status', models.CharField(choices=[('out of stock', 'Out of Stock'), ('in stock', 'In Stock')], default='in stock', max_length=20)),
                ('technology', models.CharField(blank=True, help_text='Bluetooth, Wi-Fi, USB, Ethernet, etc.', max_length=40, null=True, verbose_name='Technology')),
                ('uses_for_product', models.CharField(blank=True, help_text='Personal, Gaming, Business, etc.', max_length=50, null=True, verbose_name='Specific Uses For Product')),
                ('brand_name', models.CharField(blank=True, help_text='Example: Apple, Samsung, Sony, LG, etc.', max_length=50, null=True, verbose_name='Brand Name')),
                ('manufacturer', models.CharField(blank=True, help_text='Example: Apple, Samsung, LG, Sony, etc.', max_length=50, null=True, verbose_name='Manufacturer')),
                ('size', models.CharField(blank=True, default=0, help_text="The numeric or text version of the item's size. Example: Small, Medium, Large, X-Large, XX-Large, etc.", max_length=100, null=True, verbose_name='Size')),
                ('weight', models.CharField(blank=True, help_text="The numeric or text version of the item's weight. Example: 1.5 lbs, 2.5 lbs, etc.", max_length=10, null=True, verbose_name='Weight')),
                ('height', models.CharField(blank=True, help_text="The numeric or text version of the item's height. Example: 1.5 inches, 2.5 inches, etc.", max_length=10, null=True, verbose_name='Height')),
                ('color', models.CharField(blank=True, default='#0000', help_text='The color of the item. Example: Red, Blue, Green, etc.', max_length=200, null=True, verbose_name='Color')),
                ('shape', models.CharField(blank=True, help_text='The shape of the item. Example: Round, Square, Oval, etc.', max_length=10, null=True, verbose_name='Shape')),
                ('material_type', models.CharField(blank=True, help_text="what material is the product made out of? '\n Example: plastic, metal, wood, etc.", max_length=10, null=True, verbose_name='Material Type')),
                ('count_sold', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, help_text="Country? '\n Example: BD, China, etc.", max_length=10, null=True, verbose_name='Country')),
                ('recently_sold', models.DateTimeField(blank=True, null=True)),
                ('recently_added', models.DateTimeField(blank=True, null=True)),
                ('recently_viewed', models.DateTimeField(blank=True, null=True)),
                ('recently_updated', models.DateTimeField(blank=True, null=True)),
                ('supplier_price', models.FloatField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_ref', to='products.category')),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='company.company')),
                ('generic_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.genericname')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('content', models.CharField(default='Sale', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Taka', max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Stock Transfer')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('isPurchased', models.BooleanField(blank=True, default=False, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('avatarUrl', models.ImageField(blank=True, null=True, upload_to=products.models.review_model.upload_to)),
                ('helpful', models.IntegerField(blank=True, default=0, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('postedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('starCount', models.IntegerField(blank=True, default=0, null=True)),
                ('reviewCount', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_types', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Stock Movement',
                'verbose_name_plural': 'Product Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=60)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('qty_on_hand', models.IntegerField(default=0)),
                ('receivedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to='company.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='newLabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newLabel', to='products.newlabel'),
        ),
        migrations.AddField(
            model_name='product',
            name='saleLabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleLabel', to='products.salelabel'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=products.models.product_model.upload_to_multi)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['companyId', 'slug'], name='idx_pt_company_slug'),
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['companyId', 'name'], name='idx_pt_company_name'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('companyId', 'slug'), name='uniq_pt_company_slug'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product', 'branch'], name='idx_batch_product_branch'),
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_no__isnull', False), models.Q(('batch_no', ''), _negated=True)), fields=('product', 'branch', 'batch_no'), name='uniq_batch_product_branch_no'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='uniq_product_barcode'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['companyId', 'code'], name='idx_product_company_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['companyId', 'name'], name='idx_product_company_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['companyId', 'sku'], name='idx_product_company_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('companyId', 'code'), name='uniq_product_company_code'),
        ),
        migrations.AddIndex(
            model_name='genericname',
            index=models.Index(fields=['companyId', 'name'], name='idx_gn_company_name'),
        ),
        migrations.AddConstraint(
            model_name='genericname',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), fields=('companyId', 'name'), name='uniq_gn_company_name'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['companyId', 'name'], name='idx_brand_company_name'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), fields=('companyId', 'name'), name='uniq_brand_company_name'),
        ),
    ]
