# Generated by Django 4.2.6 on 2025-12-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_companycustomization_prescription_flags"),
        ("products", "0003_product_pharmacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="company.branch",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="companyId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["companyId", "code"], name="idx_product_company_code"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["companyId", "name"], name="idx_product_company_name"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["companyId", "sku"], name="idx_product_company_sku"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                fields=("companyId", "code"),
                name="uniq_product_company_code",
            ),
        ),
    ]
