# Generated by Django 4.2.6 on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_product_branch_product_companyid_alter_product_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="totalPurchase",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative purchased quantity added to stock (auto-incremented when receiving/purchasing).",
            ),
        ),
    ]
