# Generated by Django 4.2.6 on 2025-12-31 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_totalpurchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjustment", "Stock Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "previous_stock",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("new_stock", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="System", max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Stock Movement",
                "verbose_name_plural": "Product Stock Movements",
                "ordering": ["-created_at"],
            },
        ),
    ]
