# Generated by Django 4.2.6 on 2026-01-11 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
        ("company", "0002_companycustomization_prescription_flags"),
        ("products", "0006_productstockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_ref",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="product",
            name="track_batches",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("out of stock", "Out of Stock"), ("in stock", "In Stock")],
                default="in stock",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "companyId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_types",
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_no", models.CharField(max_length=60)),
                ("mfg_date", models.DateField(blank=True, null=True)),
                ("exp_date", models.DateField(blank=True, null=True)),
                ("qty_on_hand", models.IntegerField(default=0)),
                ("receivedAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_batches",
                        to="company.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_batches",
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("is_primary", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenericName",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "companyId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generic_names",
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "companyId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brands",
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="generic_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.genericname",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.producttype",
            ),
        ),
        migrations.AddIndex(
            model_name="producttype",
            index=models.Index(
                fields=["companyId", "slug"], name="idx_pt_company_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="producttype",
            index=models.Index(
                fields=["companyId", "name"], name="idx_pt_company_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("slug__isnull", False), models.Q(("slug", ""), _negated=True)
                ),
                fields=("companyId", "slug"),
                name="uniq_pt_company_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["product", "branch"], name="idx_batch_product_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="productbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("batch_no__isnull", False),
                    models.Q(("batch_no", ""), _negated=True),
                ),
                fields=("product", "branch", "batch_no"),
                name="uniq_batch_product_branch_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="productbarcode",
            constraint=models.UniqueConstraint(
                fields=("product", "code"), name="uniq_product_barcode"
            ),
        ),
        migrations.AddIndex(
            model_name="genericname",
            index=models.Index(
                fields=["companyId", "name"], name="idx_gn_company_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="genericname",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("name__isnull", False), models.Q(("name", ""), _negated=True)
                ),
                fields=("companyId", "name"),
                name="uniq_gn_company_name",
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["companyId", "name"], name="idx_brand_company_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("name__isnull", False), models.Q(("name", ""), _negated=True)
                ),
                fields=("companyId", "name"),
                name="uniq_brand_company_name",
            ),
        ),
    ]
